provider:
  host: https://localhost:9443

spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name: playground #change
            client-id: gjuzmH85sMutJpo3UyO5gtnXfyQa #change
            client-secret: wYlfEfxCKQmElrHNmy5MYLc2nn4a #change
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          wso2:
            issuer-uri: ${provider.host}/oauth2/token

thymeleaf:
  cache: false

  provider:
    host: https://localhost:9443
